# Generated by Django 3.2 on 2021-04-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaS_EC_App', '0002_auto_20210429_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.CharField(max_length=100, verbose_name='Mobile No'),
        ),
    ]
