# Generated by Django 3.2 on 2021-05-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaS_EC_App', '0003_alter_registration_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(help_text='It is also used as Username', max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics', verbose_name='Photo'),
        ),
    ]
